export interface ChatParams {
    _continue?: boolean,
    add_bos_token?: boolean,
    auto_max_new_tokens?: boolean,
    ban_eos_token?: boolean,
    do_sample?: boolean,
    early_stopping?: boolean,
    regenerate?: boolean,
    skip_special_tokens?: boolean,

    chat_instruct_command?: string,
    character?: string,
    context?: string,
    context_instruct?: string,
    custom_token_bans?: string,
    greeting?: string,
    grammar_string?: string,
    instruction_template?: string,
    mode?: string,
    name1?: string,
    name1_instruct?: string,
    name2?: string,
    name2_instruct?: string,
    negative_prompt?: string,
    preset?: string,
    turn_template?: string,
    user_input?: string,
    your_name?: string,

    epsilon_cutoff?: number,
    eta_cutoff?: number,
    guidance_scale?: number,
    length_penalty?: number,
    max_new_tokens?: number,
    max_tokens_second?: number,
    min_length?: number,
    mirostat_eta?: number,
    mirostat_mode?: number,
    mirostat_tau?: number,
    no_repeat_ngram_size?: number,
    num_beams?: number,
    penalty_alpha?: number,
    repetition_penalty?: number,
    repetition_penalty_range?: number,
    seed?: number,
    temperature?: number,
    top_a?: number,
    top_k?: number,
    top_p?: number,
    tfs?: number,
    truncation_length?: number,
    typical_p?: number,

    history?: {
        internal?: string[][],
        visible?: string[][],
    },

    stopping_strings?: string[],
}