name: publish
on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ./build
            ./package.json


  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Publish
        run: npm publish ./build
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}